image: python:3.11

stages:
  - install
  - qa
  - build

.install:
  stage: install
  before_script:
    - pip install uv
  script:
    - uv sync --extra dev
  artifacts:
    expire_in: 1 day
    paths:
      - .venv

install:python3.9:
  extends: .install
  image: python:3.9

install:python3.10:
  extends: .install
  image: python:3.10

install:python3.11:
  extends: .install
  image: python:3.11

install:python3.12:
  extends: .install
  image: python:3.12

install:python3.13:
  extends: .install
  image: python:3.13

install:python3.14:
  extends: .install
  image: python:3.14

ruff:
  stage: qa
  script:
    - pip install uv
    - uv run ruff check .
    - uv run ruff format --check .
  allow_failure: true
  dependencies:
    - install:python3.11

ty:
  stage: qa
  script:
    - pip install uv
    - uv run ty check
  allow_failure: true
  dependencies:
    - install:python3.11

pytest:
  stage: qa
  script:
    - pip install uv
    - uv run pytest tests/ -v
  dependencies:
    - install:python3.11

docker:
  stage: build
  image: quay.io/podman/stable
  script:
    - podman build -t gardena-smartsystem-prometheus-exporter .
  dependencies: []
